# py.exception
#
# if an exception, then the program stops, and saves the error in the file. \ problem.log
# otherwise save the open file and the time spent to open it.